version: "3.6"
services:
  postgres:
    image: postgis/postgis:12-3.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
volumes:
  db_pg:
